/** @format */

import './globals.css';
import { Toaster } from 'sonner';
import NextTopLoader from 'nextjs-toploader';
import SiteLoaderWrapper from '@/components/SiteLoaderWrapper/SiteLoaderWrapper';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className="min-h-screen flex flex-col">
        <SiteLoaderWrapper>
          {/* <Header /> */}
          <main className="flex-1 w-full max-w-7xl mx-auto px-4 md:px-6 py-6">
            <Toaster />
            <NextTopLoader />
            {children}
          </main>
        </SiteLoaderWrapper>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
